// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testsystem.actions;

import java.io.File;
import java.io.FileInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class AssignFileToFileDocument extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String filePath;
	private IMendixObject __fileObject;
	private system.proxies.FileDocument fileObject;

	public AssignFileToFileDocument(IContext context, java.lang.String filePath, IMendixObject fileObject)
	{
		super(context);
		this.filePath = filePath;
		this.__fileObject = fileObject;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.fileObject = __fileObject == null ? null : system.proxies.FileDocument.initialize(getContext(), __fileObject);

		// BEGIN USER CODE
		File file = new File(Core.getConfiguration().getResourcesPath(), filePath);
		fileObject.setName(filePath);
		Core.storeFileDocumentContent(getContext(), fileObject.getMendixObject(), new FileInputStream(file));
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AssignFileToFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
