// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testsystem.actions;

import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IFeedback.FormTarget;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;

/**
 * Action to open the form that belongs to the test.
 */
public class openForm extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String formName;
	private java.lang.String moduleName;
	private IMendixObject __test;
	private testsystem.proxies.Test test;

	public openForm(IContext context, java.lang.String formName, java.lang.String moduleName, IMendixObject test)
	{
		super(context);
		this.formName = formName;
		this.moduleName = moduleName;
		this.__test = test;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.test = __test == null ? null : testsystem.proxies.Test.initialize(getContext(), __test);

		// BEGIN USER CODE
		FeedbackHelper.addOpenFormFeedback(this.getContext(), moduleName + "/" + formName + ".mxf", formName, FormTarget.CONTENT, test.getMendixObject().getId(), new ArrayList<IMendixIdentifier>());
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "openForm";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
